<?php
    $site_url = "http://localhost/P-M-Finance-1";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <title>Document</title>
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        html,body{
            width: 100%;
            height: 100%;
        }
        .pyc{
            width: 100%;
            height: 400px;
        }
        .policy{
            margin: 80px;
        }
    </style>
</head>
<body>
    <?php
        require("./header.php");
    ?>
    <img class="pyc" src="<?php echo $site_url ?>/images/privacy_policy.jpg">
    <div class="policy">
        <h1>Policy</h1>
        <pre>

PM Finance ("Company") recognizes the importance of maintaining your privacy. PM Finance is committed to maintaining the confidentiality, integrity, and security of all information of its users. This Privacy 
Policy describes how PM Finance collects, stores, handles, and transfers certain information received from you via the use of the website on a need basis. This Privacy Policy applies to the visitors to our 
website and our existing and future customers. By visiting and/or using our website, you are accepting and consenting to the practices described in this Privacy Policy.

By using or continuing to use the website, you agree to our use of your information (including sensitive personal information as defined under the Information Technology Act 2000, applicable rules, 
notification, etc.) in accordance with this Privacy Policy, as may be amended from time to time by PM Finance at its sole discretion.
        </pre>
        <hr>
        <!-- ==============Terms of use============== -->
        <br>
        <br>
        <h1>Terms of Use</h1>
        <pre>

This Agreement sets forth the terms and conditions that apply to the access and use of the website "www.pmfinance.com," which is managed and operated by PM Finance (hereinafter collectively referred to 
as "Company"), incorporated under the laws of India and registered under the Companies Act, 1956.

This document/agreement (referred to as “Agreement”) is an electronic record in terms of the Information Technology Act, 2000, generated by a computer system, and does not require any physical or digital 
signatures. This document is published in accordance with the provisions of Rule 3 of the Information Technology (Intermediaries guidelines) 2011, that provides for the due diligence to be exercised for 
the access or usage of this website.

By accessing this website or registering your information on the website, the users (hereinafter referred to as "you" or "your") agree to be bound by this Terms of Use ("TOU"). This Agreement along with 
the Privacy Policy and Disclaimer describes our relationship with you, which will be subject to the rules, guidelines, policies, terms, and conditions applicable to any specific service provided by this 
website, and they shall be deemed to be incorporated into this TOU and considered part and parcel of this TOU.

Be sure to return to this page periodically to review the most current version of the TOU. We reserve the right at any time, at our sole discretion, to change or otherwise modify the TOU without prior notice, 
and your continued access or use of this website signifies your acceptance of the updated or modified TOU.

PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY. YOUR ACCEPTANCE OF TERMS CONTAINED HEREIN CONSTITUTES THE AGREEMENT BETWEEN YOU AND THE COMPANY FOR THE PURPOSES 
AS DEFINED HEREUNDER.
        </pre>
        <hr>
        <!-- ================Disclaimer========================= -->
        <br>
        <br>
        <h1>Disclaimer</h1>
        <pre>

PM Finance intends to provide clear information about banking products and services. The information and data on the website "www.pmfinance.com" ("Website") are generic in nature. Our efforts are to 
offer accurate and responsible data. We are not responsible for any discrepancies.

There is no purpose of violating any copyright or intellectual copyrights issues. All information provided on the portal PM Finance is subject to the discretion of the same and is likely to change without 
any notice. However, any changes in public utility will be communicated immediately on our portal.

We have tried to maintain high standards in the quality, clarity, and accuracy of the material posted on the portal. PM Finance is not legally responsible for the same in any matter whatsoever. Employees, 
partners, and associated staff of PM Finance are not accountable for any loss, harm, or damage due to the usage of information from the portal. Customers are advised to use their own discretion in such 
matters. The information provided on the portal is of a financial, insurance, and legal nature. It is a mutual understanding that customers' association with the portal will be at the customer's preference 
and risk.

Visitors to this Website/portal and every third party are hereby informed that the owners of this Website/portal are intermediaries of the banks, financial institutions, and mutual funds/AMC’s, whose 
products are dealt with on this Website/portal. It is made abundantly clear that PM Finance, its parent company, its directors, shareholders, officers, and employees are in no way responsible or liable 
for anyone for his/her investment or credit buying decision(s) (availing any kind of loans or taking credit cards through us), and every prospect/loan seeker/investor/policy-holder shall be solely 
responsible for the consequences of his/her decision(s).


<h2>Fraud-related disclaimer</h2>
BEWARE OF FRAUDULENT PHONE CALLS AND E-MAILS. PM Finance clarifies to the public that PM Finance or its officials will never ask customers/visitors to deposit any money/cash for any of our services. 
The public receiving such phone calls/emails are requested to intimate PM Finance along with details at pmfi8835@gmail.com.
        </pre>
        <hr>
        <!-- ================Grievance Redressal Mechanism========================= -->
        <br>
        <br>
        <h1>Grievance Redressal Mechanism</h1>
        <pre>

PM Finance (hereinafter referred to as the 'Company') believes that customer service is its highest priority as that is what drives growth and continuous business. The Company believes that prompt, 
efficient, and transparent service is critical to building long-lasting customer relationships. The Company is determined to ensure expeditious and efficacious handling of customer grievances, as 
well as prompt remedial & preventive action (inclusive of amendment of the Mechanism, as and when required) with the objective to avert repetitiveness.

<h2>Objectives</h2>

The Company understands that despite striving to achieve high standards of customer service excellence, there can be gaps in existing service delivery. Hence, it is critical to provide an appropriate system 
and process for customers to share their grievances. The Company aspires to create robust systems and processes to ensure effective and timely solutions to grievances with an impartial approach to set 
higher benchmarks towards effective stakeholder engagement. We have ensured that all employees of the company are aware and well-versed with our Customer Grievance Redressal Mechanism 
(“Mechanism”). Our Mechanism is based on the following principles:

Customers are always treated equitably without any prejudice at all instances.
Grievances raised by customers are acknowledged attentively and dealt with courtesy in a timely manner, addressing the key questions on why the complainant feels aggrieved or dissatisfied.
Customers are provided with multiple touchpoints to submit their grievances.
Customers are facilitated and sensitized about their rights in the Company and the mechanism to convey their grievances, as well as their rights pertaining to alternate remedies in the Company if 
they are not satisfied with the resolution of their grievances.
Grievances are investigated and redressed in a time-bound and transparent manner.
Grievances are reviewed and critically analyzed to improve the existing processes and systems to ensure that the re-occurrence of such grievances is minimized.
On the basis of this Mechanism, the Company shall ensure that an appropriate Mechanism subsists for the purpose of receiving and addressing grievances from its customers, with the aim of resolving the 
grievances equitably and expeditiously. The Mechanism encompasses adherence to the provisions of Digital Lending guidelines and other regulations stipulated by the Reserve Bank of India (RBI).

<h2>Grievance Redressal Framework</h2>

1 How to lodge a Grievance/where can a Grievance be made?

Means and Mode- Any customer having a grievance with respect to the products and services offered by the Company may reach out to the Company through any of the following channels:

Call at +91 9309844331
Email at: pmfi8835@gmail.com
Write a letter at the address: PM FINANCE PVT. LTD. at C/O- AMIT PANDURANG MARIWAR, KHANKHOJI NAGAR 4 MANEWADA CEMENT ROAD, NAGPUR, MAHARASHTRA, INDIA, 440024
Format of Grievance:

Customers are requested to necessarily provide necessary details which include:

Details of products for which grievance is made.
Date of application submitted.
Details of grievance.
Valid contact information including phone number & email ID registered with the Company at the time of registration for availing the services of PM Finance.
2 How will we address a Grievance?

a. When the customer grievance is received, we will endeavor to send an acknowledgment/a response within 48 working hours of receiving the grievance.

b. After examining the matter, we will send our final response or explain why we need more time to respond and shall endeavor to do so within 30 days of receipt of the grievance.

c. Grievance raised by mutual funds customers must be redressed as soon as possible but no later than 21 calendar days after the complaint was received.

3 Details of Nodal Grievance Redressal Officer

Name of the Officer - Mr. Manoj Wankar
Office Address - C/O- AMIT PANDURANG MARIWAR, KHANKHOJI NAGAR 4 MANEWADA CEMENT ROAD, NAGPUR, MAHARASHTRA, INDIA, 440024
Email - pmfi8835@gmail.com
Call at - 9309844331 (Lines are open Mon-Sat from 10:00 am to 7:00 pm)

<h2>Feedback from Customers</h2>

The Company will also solicit voluntary feedback from customers on an ongoing basis in a bid to improve its customer service quality.

<h2>General</h2>

Notwithstanding anything contained in this Mechanism, the Company shall ensure compliance with any additional requirements as may be prescribed under any laws/regulations either existing or arising
out of any amendment to such laws/regulations or otherwise and applicable to the Company from time to time.
         </pre>
    </div>
    <?php
        require("./footer.php");
    ?>    
</body>
</html>